// Known Perl::Critic policy short names from CPAN distributions.
// Used to determine whether a policy has a valid MetaCPAN documentation page.
// Grouped by distribution for easy maintenance.
// Source: https://trwyant.github.io/misc/all-perl-critic-policies.html

export const defined_on_metacpan: Set<string> = new Set([
    // Perl-Critic (core) v1.156
    "BuiltinFunctions::ProhibitBooleanGrep",
    "BuiltinFunctions::ProhibitComplexMappings",
    "BuiltinFunctions::ProhibitLvalueSubstr",
    "BuiltinFunctions::ProhibitReverseSortBlock",
    "BuiltinFunctions::ProhibitShiftRef",
    "BuiltinFunctions::ProhibitSleepViaSelect",
    "BuiltinFunctions::ProhibitStringyEval",
    "BuiltinFunctions::ProhibitStringySplit",
    "BuiltinFunctions::ProhibitUniversalCan",
    "BuiltinFunctions::ProhibitUniversalIsa",
    "BuiltinFunctions::ProhibitUselessTopic",
    "BuiltinFunctions::ProhibitVoidGrep",
    "BuiltinFunctions::ProhibitVoidMap",
    "BuiltinFunctions::RequireBlockGrep",
    "BuiltinFunctions::RequireBlockMap",
    "BuiltinFunctions::RequireGlobFunction",
    "BuiltinFunctions::RequireSimpleSortBlock",
    "ClassHierarchies::ProhibitAutoloading",
    "ClassHierarchies::ProhibitExplicitISA",
    "ClassHierarchies::ProhibitOneArgBless",
    "CodeLayout::ProhibitHardTabs",
    "CodeLayout::ProhibitParensWithBuiltins",
    "CodeLayout::ProhibitQuotedWordLists",
    "CodeLayout::ProhibitTrailingWhitespace",
    "CodeLayout::RequireConsistentNewlines",
    "CodeLayout::RequireTidyCode",
    "CodeLayout::RequireTrailingCommas",
    "ControlStructures::ProhibitCStyleForLoops",
    "ControlStructures::ProhibitCascadingIfElse",
    "ControlStructures::ProhibitDeepNests",
    "ControlStructures::ProhibitLabelsWithSpecialBlockNames",
    "ControlStructures::ProhibitMutatingListFunctions",
    "ControlStructures::ProhibitNegativeExpressionsInUnlessAndUntilConditions",
    "ControlStructures::ProhibitPostfixControls",
    "ControlStructures::ProhibitUnlessBlocks",
    "ControlStructures::ProhibitUnreachableCode",
    "ControlStructures::ProhibitUntilBlocks",
    "ControlStructures::ProhibitYadaOperator",
    "Documentation::PodSpelling",
    "Documentation::RequirePackageMatchesPodName",
    "Documentation::RequirePodAtEnd",
    "Documentation::RequirePodLinksIncludeText",
    "Documentation::RequirePodSections",
    "ErrorHandling::RequireCarping",
    "ErrorHandling::RequireCheckingReturnValueOfEval",
    "InputOutput::ProhibitBacktickOperators",
    "InputOutput::ProhibitBarewordDirHandles",
    "InputOutput::ProhibitBarewordFileHandles",
    "InputOutput::ProhibitExplicitStdin",
    "InputOutput::ProhibitInteractiveTest",
    "InputOutput::ProhibitJoinedReadline",
    "InputOutput::ProhibitOneArgSelect",
    "InputOutput::ProhibitReadlineInForLoop",
    "InputOutput::ProhibitTwoArgOpen",
    "InputOutput::RequireBracedFileHandleWithPrint",
    "InputOutput::RequireBriefOpen",
    "InputOutput::RequireCheckedClose",
    "InputOutput::RequireCheckedOpen",
    "InputOutput::RequireCheckedSyscalls",
    "InputOutput::RequireEncodingWithUTF8Layer",
    "Miscellanea::ProhibitFormats",
    "Miscellanea::ProhibitTies",
    "Miscellanea::ProhibitUnrestrictedNoCritic",
    "Miscellanea::ProhibitUselessNoCritic",
    "Modules::ProhibitAutomaticExportation",
    "Modules::ProhibitConditionalUseStatements",
    "Modules::ProhibitEvilModules",
    "Modules::ProhibitExcessMainComplexity",
    "Modules::ProhibitMultiplePackages",
    "Modules::RequireBarewordIncludes",
    "Modules::RequireEndWithOne",
    "Modules::RequireExplicitPackage",
    "Modules::RequireFilenameMatchesPackage",
    "Modules::RequireNoMatchVarsWithUseEnglish",
    "Modules::RequireVersionVar",
    "NamingConventions::Capitalization",
    "NamingConventions::ProhibitAmbiguousNames",
    "Objects::ProhibitIndirectSyntax",
    "References::ProhibitDoubleSigils",
    "RegularExpressions::ProhibitCaptureWithoutTest",
    "RegularExpressions::ProhibitComplexRegexes",
    "RegularExpressions::ProhibitEnumeratedClasses",
    "RegularExpressions::ProhibitEscapedMetacharacters",
    "RegularExpressions::ProhibitFixedStringMatches",
    "RegularExpressions::ProhibitSingleCharAlternation",
    "RegularExpressions::ProhibitUnusedCapture",
    "RegularExpressions::ProhibitUnusualDelimiters",
    "RegularExpressions::ProhibitUselessTopic",
    "RegularExpressions::RequireBracesForMultiline",
    "RegularExpressions::RequireDotMatchAnything",
    "RegularExpressions::RequireExtendedFormatting",
    "RegularExpressions::RequireLineBoundaryMatching",
    "Subroutines::ProhibitAmpersandSigils",
    "Subroutines::ProhibitBuiltinHomonyms",
    "Subroutines::ProhibitExcessComplexity",
    "Subroutines::ProhibitExplicitReturnUndef",
    "Subroutines::ProhibitManyArgs",
    "Subroutines::ProhibitNestedSubs",
    "Subroutines::ProhibitReturnSort",
    "Subroutines::ProhibitSubroutinePrototypes",
    "Subroutines::ProhibitUnusedPrivateSubroutines",
    "Subroutines::ProtectPrivateSubs",
    "Subroutines::RequireArgUnpacking",
    "Subroutines::RequireFinalReturn",
    "TestingAndDebugging::ProhibitNoStrict",
    "TestingAndDebugging::ProhibitNoWarnings",
    "TestingAndDebugging::ProhibitProlongedStrictureOverride",
    "TestingAndDebugging::RequireTestLabels",
    "TestingAndDebugging::RequireUseStrict",
    "TestingAndDebugging::RequireUseWarnings",
    "ValuesAndExpressions::ProhibitCommaSeparatedStatements",
    "ValuesAndExpressions::ProhibitComplexVersion",
    "ValuesAndExpressions::ProhibitConstantPragma",
    "ValuesAndExpressions::ProhibitEmptyQuotes",
    "ValuesAndExpressions::ProhibitEscapedCharacters",
    "ValuesAndExpressions::ProhibitImplicitNewlines",
    "ValuesAndExpressions::ProhibitInterpolationOfLiterals",
    "ValuesAndExpressions::ProhibitLeadingZeros",
    "ValuesAndExpressions::ProhibitLongChainsOfMethodCalls",
    "ValuesAndExpressions::ProhibitMagicNumbers",
    "ValuesAndExpressions::ProhibitMismatchedOperators",
    "ValuesAndExpressions::ProhibitMixedBooleanOperators",
    "ValuesAndExpressions::ProhibitNoisyQuotes",
    "ValuesAndExpressions::ProhibitQuotesAsQuotelikeOperatorDelimiters",
    "ValuesAndExpressions::ProhibitSpecialLiteralHeredocTerminator",
    "ValuesAndExpressions::ProhibitVersionStrings",
    "ValuesAndExpressions::RequireConstantVersion",
    "ValuesAndExpressions::RequireInterpolationOfMetachars",
    "ValuesAndExpressions::RequireNumberSeparators",
    "ValuesAndExpressions::RequireQuotedHeredocTerminator",
    "ValuesAndExpressions::RequireUpperCaseHeredocTerminator",
    "Variables::ProhibitAugmentedAssignmentInDeclaration",
    "Variables::ProhibitConditionalDeclarations",
    "Variables::ProhibitEvilVariables",
    "Variables::ProhibitLocalVars",
    "Variables::ProhibitMatchVars",
    "Variables::ProhibitPackageVars",
    "Variables::ProhibitPerl4PackageNames",
    "Variables::ProhibitPunctuationVars",
    "Variables::ProhibitReusedNames",
    "Variables::ProhibitUnusedVariables",
    "Variables::ProtectPrivateVars",
    "Variables::RequireInitializationForLocalVars",
    "Variables::RequireLexicalLoopIterators",
    "Variables::RequireLocalizedPunctuationVars",
    "Variables::RequireNegativeIndices",

    // Perl-Critic-Bangs v1.14
    "Bangs::ProhibitBitwiseOperators",
    "Bangs::ProhibitCommentedOutCode",
    "Bangs::ProhibitDebuggingModules",
    "Bangs::ProhibitFlagComments",
    "Bangs::ProhibitNoPlan",
    "Bangs::ProhibitNumberedNames",
    "Bangs::ProhibitRefProtoOrProto",
    "Bangs::ProhibitUselessRegexModifiers",
    "Bangs::ProhibitVagueNames",

    // Perl-Critic-CognitiveComplexity v0.5
    "CognitiveComplexity::ProhibitExcessCognitiveComplexity",

    // Perl-Critic-Community v1.0.4
    "Community::AmpersandSubCalls",
    "Community::ArrayAssignAref",
    "Community::BarewordFilehandles",
    "Community::ConditionalDeclarations",
    "Community::ConditionalImplicitReturn",
    "Community::DeprecatedFeatures",
    "Community::DiscouragedModules",
    "Community::DollarAB",
    "Community::Each",
    "Community::EmptyReturn",
    "Community::IndirectObjectNotation",
    "Community::LexicalForeachIterator",
    "Community::LoopOnHash",
    "Community::ModPerl",
    "Community::MultidimensionalArrayEmulation",
    "Community::OpenArgs",
    "Community::OverloadOptions",
    "Community::POSIXImports",
    "Community::PackageMatchesFilename",
    "Community::PreferredAlternatives",
    "Community::Prototypes",
    "Community::SplitQuotedPattern",
    "Community::StrictWarnings",
    "Community::Threads",
    "Community::Wantarray",
    "Community::WarningsSwitch",
    "Community::WhileDiamondDefaultAssignment",

    // Perl-Critic-Compatibility v1.001
    "Compatibility::ProhibitThreeArgumentOpen",

    // Perl-Critic-Dancer2 v0.4100
    "Dancer2::ProhibitDeprecatedKeywords",
    "Dancer2::ProhibitUnrecommendedKeywords",
    "Dancer2::ReturnNotNecessary",

    // Perl-Critic-Deprecated v1.119
    "Miscellanea::RequireRcsKeywords",
    "NamingConventions::ProhibitMixedCaseSubs",
    "NamingConventions::ProhibitMixedCaseVars",

    // Perl-Critic-Dynamic v0.05
    "Dynamic::ValidateAgainstSymbolTable",

    // Perl-Critic-Freenode v1.0.4 (deprecated, renamed to Community)
    "Freenode::AmpersandSubCalls",
    "Freenode::ArrayAssignAref",
    "Freenode::BarewordFilehandles",
    "Freenode::ConditionalDeclarations",
    "Freenode::ConditionalImplicitReturn",
    "Freenode::DeprecatedFeatures",
    "Freenode::DiscouragedModules",
    "Freenode::DollarAB",
    "Freenode::Each",
    "Freenode::EmptyReturn",
    "Freenode::IndirectObjectNotation",
    "Freenode::LexicalForeachIterator",
    "Freenode::LoopOnHash",
    "Freenode::ModPerl",
    "Freenode::MultidimensionalArrayEmulation",
    "Freenode::OpenArgs",
    "Freenode::OverloadOptions",
    "Freenode::POSIXImports",
    "Freenode::PackageMatchesFilename",
    "Freenode::PreferredAlternatives",
    "Freenode::Prototypes",
    "Freenode::StrictWarnings",
    "Freenode::Threads",
    "Freenode::Wantarray",
    "Freenode::WarningsSwitch",
    "Freenode::WhileDiamondDefaultAssignment",

    // Perl-Critic-Grape v0.0.7
    "CodeLayout::RequireParensWithBuiltins",
    "ControlStructures::ProhibitInlineDo",
    "References::ProhibitRefChecks",
    "References::RequireSigils",
    "Variables::ProhibitTopicIterator",

    // Perl-Critic-Itch v0.07
    "CodeLayout::ProhibitHashBarewords",

    // Perl-Critic-Lax v0.014
    "Lax::ProhibitComplexMappings::LinesNotStatements",
    "Lax::ProhibitEmptyQuotes::ExceptAsFallback",
    "Lax::ProhibitLeadingZeros::ExceptChmod",
    "Lax::ProhibitStringyEval::ExceptForRequire",
    "Lax::RequireConstantOnLeftSideOfEquality::ExceptEq",
    "Lax::RequireEndWithTrueConst",
    "Lax::RequireExplicitPackage::ExceptForPragmata",

    // Perl-Critic-Mardem v0.06
    "Mardem::ProhibitBlockComplexity",
    "Mardem::ProhibitConditionComplexity",
    "Mardem::ProhibitFileSize",
    "Mardem::ProhibitLargeBlock",
    "Mardem::ProhibitLargeFile",
    "Mardem::ProhibitLargeSub",
    "Mardem::ProhibitManyConditionsInSub",
    "Mardem::ProhibitReturnBooleanAsInt",

    // Perl-Critic-More v1.003
    "CodeLayout::RequireASCII",
    "Editor::RequireEmacsFileVariables",
    "ErrorHandling::RequireUseOfExceptions",
    "Modules::PerlMinimumVersion",
    "Modules::RequirePerlVersion",
    "ValuesAndExpressions::RequireConstantOnLeftSideOfEquality",
    "ValuesAndExpressions::RestrictLongStrings",

    // Perl-Critic-Moose v1.05
    "Moose::ProhibitDESTROYMethod",
    "Moose::ProhibitLazyBuild",
    "Moose::ProhibitMultipleWiths",
    "Moose::ProhibitNewMethod",
    "Moose::RequireCleanNamespace",
    "Moose::RequireMakeImmutable",

    // Perl-Critic-Nits v1.0.0
    "ValuesAndExpressions::ProhibitAccessOfPrivateData",

    // Perl-Critic-PetPeeves-JTRAMMELL v0.04
    "Variables::ProhibitUselessInitialization",

    // Perl-Critic-PJCJ v0.2.5
    "CodeLayout::ProhibitLongLines",
    "ValuesAndExpressions::RequireConsistentQuoting",

    // Perl-Critic-Plicease v0.10
    "Plicease::ProhibitLeadingZeros",
    "Plicease::ProhibitSignaturesAndAtUnderscore",
    "Plicease::ProhibitSpecificModules",
    "Plicease::ProhibitUnicodeDigitInRegexp",

    // Perl-Critic-PolicyBundle-SNEZ v0.03
    "CodeLayout::RequireBreakBeforeOperator",
    "CodeLayout::RequireKRBracing",
    "CodeLayout::RequireKRParens",
    "CodeLayout::RequireSpaceAroundBinaryOperators",
    "ControlStructures::ProhibitMultipleSubscripts",
    "ValuesAndExpressions::ProhibitListsInMultiConstants",

    // Perl-Critic-Pulp v100
    "CodeLayout::ProhibitFatCommaNewline",
    "CodeLayout::ProhibitIfIfSameLine",
    "CodeLayout::RequireFinalSemicolon",
    "CodeLayout::RequireTrailingCommaAtNewline",
    "Compatibility::ConstantLeadingUnderscore",
    "Compatibility::ConstantPragmaHash",
    "Compatibility::Gtk2Constants",
    "Compatibility::PerlMinimumVersionAndWhy",
    "Compatibility::PodMinimumVersion",
    "Compatibility::ProhibitUnixDevNull",
    "Documentation::ProhibitAdjacentLinks",
    "Documentation::ProhibitBadAproposMarkup",
    "Documentation::ProhibitDuplicateHeadings",
    "Documentation::ProhibitDuplicateSeeAlso",
    "Documentation::ProhibitLinkToSelf",
    "Documentation::ProhibitParagraphEndComma",
    "Documentation::ProhibitParagraphTwoDots",
    "Documentation::ProhibitUnbalancedParens",
    "Documentation::ProhibitVerbatimMarkup",
    "Documentation::RequireEndBeforeLastPod",
    "Documentation::RequireFilenameMarkup",
    "Documentation::RequireFinalCut",
    "Documentation::RequireLinkedURLs",
    "Miscellanea::TextDomainPlaceholders",
    "Miscellanea::TextDomainUnused",
    "Modules::ProhibitModuleShebang",
    "Modules::ProhibitPOSIXimport",
    "Modules::ProhibitUseQuotedVersion",
    "ValuesAndExpressions::ConstantBeforeLt",
    "ValuesAndExpressions::NotWithCompare",
    "ValuesAndExpressions::ProhibitArrayAssignAref",
    "ValuesAndExpressions::ProhibitBarewordDoubleColon",
    "ValuesAndExpressions::ProhibitDuplicateHashKeys",
    "ValuesAndExpressions::ProhibitEmptyCommas",
    "ValuesAndExpressions::ProhibitFiletest_f",
    "ValuesAndExpressions::ProhibitNullStatements",
    "ValuesAndExpressions::ProhibitUnknownBackslash",
    "ValuesAndExpressions::RequireNumericVersion",
    "ValuesAndExpressions::UnexpandedSpecialLiteral",

    // Perl-Critic-RENEEB v2.05
    "RegularExpressions::RequireExtendedFormattingExceptForSplit",
    "Reneeb::Capitalization",
    "Reneeb::ProhibitBlockEval",
    "Reneeb::ProhibitGrepToGetFirstFoundElement",
    "Reneeb::RequirePostderef",

    // Perl-Critic-StricterSubs v0.08
    "Modules::RequireExplicitInclusion",
    "Subroutines::ProhibitCallsToUndeclaredSubs",
    "Subroutines::ProhibitCallsToUnexportedSubs",
    "Subroutines::ProhibitExportingUndeclaredSubs",
    "Subroutines::ProhibitQualifiedSubDeclarations",

    // Perl-Critic-Storable v0.01
    "Storable::ProhibitStoreOrFreeze",

    // Perl-Critic-Swift v1.0.3
    "CodeLayout::RequireUseUTF8",
    "Documentation::RequirePODUseEncodingUTF8",

    // Perl-Critic-Tics v0.010
    "Tics::ProhibitLongLines",
    "Tics::ProhibitManyArrows",
    "Tics::ProhibitUseBase",

    // Perl-Critic-TooMuchCode v0.19
    "TooMuchCode::ProhibitDuplicateLiteral",
    "TooMuchCode::ProhibitDuplicateSub",
    "TooMuchCode::ProhibitExcessiveColons",
    "TooMuchCode::ProhibitExtraStricture",
    "TooMuchCode::ProhibitLargeBlock",
    "TooMuchCode::ProhibitLargeTryBlock",
    "TooMuchCode::ProhibitUnnecessaryScalarKeyword",
    "TooMuchCode::ProhibitUnnecessaryUTF8Pragma",
    "TooMuchCode::ProhibitUnusedConstant",
    "TooMuchCode::ProhibitUnusedImport",
    "TooMuchCode::ProhibitUnusedInclude",

    // Perl-Critic-logicLAB (individual distributions)
    "logicLAB::ModuleBlacklist",
    "logicLAB::ProhibitShellDispatch",
    "logicLAB::ProhibitUseLib",
    "logicLAB::RequirePackageNamePattern",
    "logicLAB::RequireParamsValidate",
    "logicLAB::RequireSheBang",
    "logicLAB::RequireVersionFormat",

    // Standalone policy distributions
    "BuiltinFunctions::ProhibitDeleteOnArrays",
    "BuiltinFunctions::ProhibitForeach",
    "BuiltinFunctions::ProhibitReturnOr",
    "Catalyst::ProhibitUnreachableCode",
    "CodeLayout::ProhibitSpaceIndentation",
    "CodeLayout::TabIndentSpaceAlign",
    "ControlStructures::ProhibitReturnInDoBlock",
    "ControlStructures::ProhibitReturnInMappingBlock",
    "ControlStructures::ProhibitSwitchStatements",
    "Documentation::RequirePod",
    "Dynamic::NoIndirect",
    "InputOutput::ProhibitHighPrecedentLogicalOperatorErrorHandling",
    "Modules::ProhibitUseLib",
    "Modules::RequireExplicitPackage::ObjectPad",
    "Moo::ProhibitMakeImmutable",
    "Operators::ProhibitSmartmatch",
    "Plicease::ProhibitArrayAssignAref",
    "References::ProhibitComplexDoubleSigils",
    "RegularExpressions::ProhibitEmptyAlternatives",
    "RegularExpressions::RequireDefault",
    "Subroutines::ProhibitAmbiguousFunctionCalls",
    "Subroutines::ProhibitLvalueMethods",
    "TryTiny::RequireBlockTermination",
    "TryTiny::RequireUse",
    "ValuesAndExpressions::PreventSQLInjection",
    "ValuesAndExpressions::ProhibitEmptyPostfixLoop",
    "ValuesAndExpressions::ProhibitFiletest_rwxRWX",
    "ValuesAndExpressions::ProhibitSingleArgArraySlice",
    "Variables::NameReuse",
    "Variables::ProhibitLoopOnHash",
    "Variables::ProhibitNumericNamesWithLeadingZero",
    "Variables::ProhibitUnusedVarsStricter",
    "Variables::RequireHungarianNotation",
]);

